export const OBRAMAT_CATALOGO: ObramatProducto[] = [
  { sku: "10967145", nombre: "KG UNIDAD KILO 17", formato: "Unidad", precioUnitario: 0.1, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10967432", nombre: "KG UNIDAD KILO Proyal 20", formato: "Unidad", precioUnitario: 0.18, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10967061", nombre: "KG UNIDAD KILO Proyal XXI 20", formato: "Unidad", precioUnitario: 0.21, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10967012", nombre: "KG UNIDAD KILO 17", formato: "Unidad", precioUnitario: 0.11, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10967411", nombre: "KG UNIDAD KILO KG UNIDAD KILO 17    17", formato: "Unidad", precioUnitario: 0.35, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10648911", nombre: "KG UNIDAD KILO KG UNIDAD KILO 17    17", formato: "Unidad", precioUnitario: 0.35, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10966935", nombre: "ESCAYOLAS PEGAMENTOS 17", formato: "Unidad", precioUnitario: 0.16, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10301424", nombre: "KG UNIDAD KILO 10", formato: "Unidad", precioUnitario: 0.46, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10755920", nombre: "GRAVA VOLCANICA 20    KG SACO KILO KG SACO KILO KG SACO KILO KG SACO KILO", formato: "Unidad", precioUnitario: 0.23, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10756032", nombre: "GRAVA VOLCANICA 1000    20    15    20    20", formato: "Unidad", precioUnitario: 0.25, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10755941", nombre: "GRAVA VOLCANICA 1000    20    15    20    20", formato: "Unidad", precioUnitario: 0.25, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10755962", nombre: "GRAVA VOLCANICA 1000    20    15    20    20", formato: "Unidad", precioUnitario: 0.25, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10755990", nombre: "GRAVA VOLCANICA 1000    20    15    20    20", formato: "Unidad", precioUnitario: 0.25, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10756011", nombre: "GRAVA VOLCANICA 1000    20    15    20    20", formato: "Unidad", precioUnitario: 0.25, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10355415", nombre: "ARENA, GRAVA Y ARCILLA Fina 0-2    MM SACO KILO", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10355401", nombre: "ARENA, GRAVA Y ARCILLA Normal 0-4/5    Barrecha Fina 0-12", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10355422", nombre: "ARENA, GRAVA Y ARCILLA Normal 0-4/5    Barrecha Fina 0-12", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10355436", nombre: "MM SACA KILO Arena Normal 0-4", formato: "Unidad", precioUnitario: 0.03, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10355443", nombre: "MM SACA KILO de hormigón, asilamiento de forjados, cubiertas y soleras. estructuras de hormigón, rellenos y nivelaciones. Barrecha Fina 0-12", formato: "Unidad", precioUnitario: 0.03, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "25031586", nombre: "MM SACA KILO L SACO LITRO L SACO LITRO Grava Canto Rodado 22-40", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "25035371", nombre: "MM SACA KILO 50    50    Grava Balastro 40-70", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "25035347", nombre: "MM SACA KILO 50    50    Grava Balastro 40-70", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10479924", nombre: "MM SACA KILO 50    50    Grava Balastro 40-70", formato: "Unidad", precioUnitario: 0.04, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "10677975", nombre: "KG SACO KILO KG SACO KILO KG SACO KILO 25    25    25", formato: "Unidad", precioUnitario: 0.44, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "25054431", nombre: "KG SACO KILO KG SACO KILO KG SACO KILO 25    25    25", formato: "Unidad", precioUnitario: 0.44, categoriaId: "mat-cons", subcategoria: "General", paginaCatalogo: 10 },
  { sku: "25028586", nombre: "UNIDAD LITRO", formato: "Unidad", precioUnitario: 25.6, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10209983", nombre: "L UNIDAD LITRO", formato: "Unidad", precioUnitario: 9.06, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10392452", nombre: "L UNIDAD LITRO 25", formato: "Unidad", precioUnitario: 7.52, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10590153", nombre: "BOTE LITRO", formato: "Unidad", precioUnitario: 3.8, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703462", nombre: "COLOR GR UNIDAD KILO Amarillo 500", formato: "Unidad", precioUnitario: 13.8, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703413", nombre: "COLOR GR UNIDAD KILO Rojo 800", formato: "Unidad", precioUnitario: 10.69, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703441", nombre: "COLOR GR UNIDAD KILO Naranja 800", formato: "Unidad", precioUnitario: 10.69, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703406", nombre: "COLOR GR UNIDAD KILO Pardo 800", formato: "Unidad", precioUnitario: 10.69, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703490", nombre: "COLOR GR UNIDAD KILO Negro 800", formato: "Unidad", precioUnitario: 10.69, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703476", nombre: "COLOR GR UNIDAD KILO Ocre 800", formato: "Unidad", precioUnitario: 10.69, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10703532", nombre: "COLOR GR UNIDAD KILO Verde 1 600", formato: "Unidad", precioUnitario: 43.6, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25087034", nombre: "UNIDAD LITRO Blanco", formato: "Unidad", precioUnitario: 17.93, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25087033", nombre: "UNIDAD LITRO Gris", formato: "Unidad", precioUnitario: 17.93, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25087035", nombre: "UNIDAD LITRO Marrón", formato: "Unidad", precioUnitario: 17.93, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25034390", nombre: "UNIDAD LITRO Transparente", formato: "Unidad", precioUnitario: 27.41, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25034358", nombre: "UNIDAD LITRO Blanco", formato: "Unidad", precioUnitario: 14.92, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25034392", nombre: "UNIDAD LITRO Gris", formato: "Unidad", precioUnitario: 14.92, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "25034380", nombre: "UNIDAD LITRO Marrón", formato: "Unidad", precioUnitario: 14.92, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10977344", nombre: "ML UNIDAD LITRO Blanco 300", formato: "Unidad", precioUnitario: 26.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10668875", nombre: "ML UNIDAD LITRO Beige 300", formato: "Unidad", precioUnitario: 26.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10977323", nombre: "ML UNIDAD LITRO Marrón 300", formato: "Unidad", precioUnitario: 26.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10977330", nombre: "ML UNIDAD LITRO Gris 300", formato: "Unidad", precioUnitario: 26.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10977351", nombre: "ML UNIDAD LITRO Negro 300", formato: "Unidad", precioUnitario: 26.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10519544", nombre: "ML UNIDAD LITRO Blanco 600", formato: "Unidad", precioUnitario: 19.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10519586", nombre: "ML UNIDAD LITRO Gris 600", formato: "Unidad", precioUnitario: 19.63, categoriaId: "pintura", subcategoria: "General", paginaCatalogo: 156 },
  { sku: "10762010", nombre: "LÁMINA MULTICAPA VISCOLAM-35 2 10", formato: "Unidad", precioUnitario: 3.01, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10560830", nombre: "LÁMINA MULTICAPA MAD-4 4 6", formato: "Unidad", precioUnitario: 8.69, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "25073118", nombre: "LÁMINA MULTICAPA MAD-4 4 6", formato: "Unidad", precioUnitario: 8.69, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10267761", nombre: "LÁMINA MULTICAPA", formato: "Unidad", precioUnitario: 10.55, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10486784", nombre: "LÁMINA MULTICAPA", formato: "Unidad", precioUnitario: 10.55, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "25073789", nombre: "PANEL ESPUMA POLIURETANO", formato: "Unidad", precioUnitario: 7.99, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10486791", nombre: "PANEL ESPUMA POLIURETANO", formato: "Unidad", precioUnitario: 15.97, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10486805", nombre: "PANEL ESPUMA POLIURETANO", formato: "Unidad", precioUnitario: 15.97, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "25073791", nombre: "PANEL ESPUMA POLIURETANO", formato: "Unidad", precioUnitario: 15.97, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10763802", nombre: "CHOVASTAR Solid 0,6 50x50x3 6 uds 1,5 Ignífugo    Consumo: 0,4L/m².", formato: "Unidad", precioUnitario: 45.33, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10595375", nombre: "CHOVASTAR Marina 0,6 50x50x3 10 uds 2,5 Pegar con Chovastar    L UNIDAD LITRO", formato: "Unidad", precioUnitario: 13.27, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10763781", nombre: "CHOVASTAR Pirámide 0,7 45x45x4.3 8 uds 1,62 Autoadhesivo    5", formato: "Unidad", precioUnitario: 5.58, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10494673", nombre: "CHOVASTAR", formato: "Unidad", precioUnitario: 0.0, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10494694", nombre: "CHOVASTAR", formato: "Unidad", precioUnitario: 0.0, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10763795", nombre: "CHOVASTAR Sierra 0,75 45x45x4.3 8 uds 1,62 Autoadhesivo    20", formato: "Unidad", precioUnitario: 5.1, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10393215", nombre: "DE MADERA", formato: "Unidad", precioUnitario: 16.5, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10987781", nombre: "PERFORADO TONGA", formato: "Unidad", precioUnitario: 14.86, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10233146", nombre: "UNIDAD METRO Primario 3,70m", formato: "Unidad", precioUnitario: 1.05, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10233132", nombre: "UNIDAD METRO Secundario 0,60m", formato: "Unidad", precioUnitario: 1.02, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10233160", nombre: "UNIDAD METRO Secundario 1,20m", formato: "Unidad", precioUnitario: 1.04, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10035732", nombre: "UNIDAD METRO Angular 3m", formato: "Unidad", precioUnitario: 0.8, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10974075", nombre: "PIEZA DE SUSPENSIÓN PRIMARIO/SECUNDARIO Métrica M6.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10661154", nombre: "PIEZA DE SUSPENSIÓN PRIMARIO/SECUNDARIO Primario 3,70m", formato: "Unidad", precioUnitario: 1.56, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10661175", nombre: "PIEZA DE SUSPENSIÓN PRIMARIO/SECUNDARIO Secundario 0,60m", formato: "Unidad", precioUnitario: 1.57, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "10661161", nombre: "PIEZA DE SUSPENSIÓN PRIMARIO/SECUNDARIO Secundario 1,20m", formato: "Unidad", precioUnitario: 1.56, categoriaId: "madera", subcategoria: "General", paginaCatalogo: 104 },
  { sku: "25047487", nombre: "PLACA POLIESTIRENO EXPANDIDO SATE", formato: "Unidad", precioUnitario: 2.3, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25047483", nombre: "PLACA POLIESTIRENO EXPANDIDO SATE", formato: "Unidad", precioUnitario: 6.9, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25047485", nombre: "PLACA POLIESTIRENO EXPANDIDO (EPS)", formato: "Unidad", precioUnitario: 1.68, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25047484", nombre: "PLACA POLIESTIRENO EXPANDIDO (EPS)", formato: "Unidad", precioUnitario: 3.33, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25047486", nombre: "PLACA POLIESTIRENO EXPANDIDO (EPS)", formato: "Unidad", precioUnitario: 10.24, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25096149", nombre: "PLACA POLIESTIRENO EXPANDIDO (EPS) 10", formato: "Unidad", precioUnitario: 12.8, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10989923", nombre: "PLACA POLIESTIRENO EXTRUIDO (XPS)", formato: "Unidad", precioUnitario: 5.01, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10989930", nombre: "PLACA POLIESTIRENO EXTRUIDO (XPS)", formato: "Unidad", precioUnitario: 6.27, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10989951", nombre: "PLACA POLIESTIRENO EXTRUIDO (XPS)", formato: "Unidad", precioUnitario: 7.52, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10989965", nombre: "PLACA POLIESTIRENO EXTRUIDO (XPS)", formato: "Unidad", precioUnitario: 10.03, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10989986", nombre: "PLACA POLIESTIRENO EXTRUIDO (XPS) 10", formato: "Unidad", precioUnitario: 12.53, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10989993", nombre: "PLACA POLIESTIRENO EXTRUIDO (XPS)", formato: "Unidad", precioUnitario: 4.96, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10595214", nombre: "L BOTE LITRO", formato: "Unidad", precioUnitario: 6.65, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10595221", nombre: "L BOTE LITRO", formato: "Unidad", precioUnitario: 6.54, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25088845", nombre: "AISLAMIENTO TERMOREFLEX ONE", formato: "Unidad", precioUnitario: 3.0, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25043643", nombre: "AISLAMIENTO TERMOREFLEX ONE", formato: "Unidad", precioUnitario: 119.0, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25042571", nombre: "AISLAMIENTO TERMOREFLEX ALU", formato: "Unidad", precioUnitario: 3.5, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25088847", nombre: "AISLAMIENTO AIR BUR TERMIC SYC", formato: "Unidad", precioUnitario: 105.0, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25088843", nombre: "AISLAMIENTO AIR BUR TERMIC SYC", formato: "Unidad", precioUnitario: 4.25, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25107934", nombre: "MULTICAPA HYBRIS 120x41 1,96", formato: "Unidad", precioUnitario: 5.81, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "25107933", nombre: "MULTICAPA HYBRIS 120x61 2.92 m2", formato: "Unidad", precioUnitario: 5.8, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10365334", nombre: "M UNIDAD METRO", formato: "Unidad", precioUnitario: 4.95, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10365341", nombre: "M UNIDAD METRO", formato: "Unidad", precioUnitario: 4.5, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10365355", nombre: "M UNIDAD METRO", formato: "Unidad", precioUnitario: 4.95, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10365362", nombre: "UNIDAD METRO", formato: "Unidad", precioUnitario: 1.64, categoriaId: "cocinas", subcategoria: "General", paginaCatalogo: 82 },
  { sku: "10962546", nombre: "UNIDAD Teja 46x28 cm", formato: "Unidad", precioUnitario: 1.65, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10364984", nombre: "UNIDAD Caballete clásico", formato: "Unidad", precioUnitario: 8.4, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10364970", nombre: "UNIDAD Remate angular", formato: "Unidad", precioUnitario: 8.4, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10364991", nombre: "UNIDAD Teja ventilación", formato: "Unidad", precioUnitario: 16.95, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10474996", nombre: "UNIDAD Teja 45.4x28.6 cm", formato: "Unidad", precioUnitario: 1.8, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10475010", nombre: "UNIDAD Caballete clásico", formato: "Unidad", precioUnitario: 8.4, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10475024", nombre: "UNIDAD Remate angular", formato: "Unidad", precioUnitario: 7.75, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10475031", nombre: "UNIDAD Teja ventilación", formato: "Unidad", precioUnitario: 17.95, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25038732", nombre: "UNIDAD Teja 42x33.1 cm", formato: "Unidad", precioUnitario: 1.34, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25021452", nombre: "UNIDAD Teja Masa latina 42x33 cm 1", formato: "Unidad", precioUnitario: 1.25, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10802813", nombre: "UNIDAD Remate angular", formato: "Unidad", precioUnitario: 4.6, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10802792", nombre: "UNIDAD Cumbrera", formato: "Unidad", precioUnitario: 4.8, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10802771", nombre: "UNIDAD Teja ventilación 1", formato: "Unidad", precioUnitario: 12.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25038739", nombre: "UNIDAD Teja ventilación", formato: "Unidad", precioUnitario: 12.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25031742", nombre: "PLACAS Y HORNOS potencia.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10599022", nombre: "PLACAS Y HORNOS", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10726240", nombre: "PLACAS Y HORNOS radiantes y 9 niveles de potencia.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25029168", nombre: "PLACAS Y HORNOS Fast-Click.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10403372", nombre: "PLACAS Y HORNOS de potencia. Indicador de calor residual.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25029094", nombre: "MICROONDAS ENCASTRABLE Volumen 20 L.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25121600", nombre: "ACABADO INOXIDABLE Volumen 70L.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25102555", nombre: "ACABADO INOXIDABLE Capacidad de 74 L.  Volumen 77 l.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10904040", nombre: "ACABADO INOXIDABLE Capacidad de 74 L.  Volumen 77 l.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10178434", nombre: "MUEBLE blanco. Modelo: AIR101 .", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "10892735", nombre: "MODELO CM UNIDAD TL6310 blanca Ancho 60 339 m3/h", formato: "Unidad", precioUnitario: 66.0, categoriaId: "ceramica", subcategoria: "General", paginaCatalogo: 120 },
  { sku: "25118236", nombre: "HORMIGONERA ELÉCTRICA Peso: 55kg", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25119960", nombre: "HORMIGONERA ELÉCTRICA Peso: 49kg", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25119961", nombre: "HORMIGONERA ELÉCTRICA Peso: 62kg", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25118234", nombre: "HORMIGONERA ELÉCTRICA piñon conico Protección IP45 Peso: 95kg", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25118235", nombre: "HORMIGONERA ELÉCTRICA piñon cónico. Protección IP45 Peso: 100kg", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10724175", nombre: "HORMIGONERA ELÉCTRICA Peso 5,5 kg", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10424043", nombre: "PASTERA Capacidad 190l. Reforzada.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25044714", nombre: "PASTERA Rueda hinchable.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25118267", nombre: "PASTERA Refuerzo frontal. Bastidor de Ø 32 mm. Rueda impinchable", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25044695", nombre: "PASTERA Universal. Neumática.  Universal. Maciza.  Capacidad 190L. Reforzada 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25044721", nombre: "PASTERA Universal. Neumática.  Universal. Maciza.  Capacidad 190L. Reforzada 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25072521", nombre: "PASTERA Universal. Neumática.  Universal. Maciza.  Capacidad 190L. Reforzada 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "25044715", nombre: "PASTERA elevados en grúa. Rueda hinchable.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10247496", nombre: "CM UNIDAD 60 x 60", formato: "Unidad", precioUnitario: 67.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10247503", nombre: "CM UNIDAD 80 x 80", formato: "Unidad", precioUnitario: 90.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10247475", nombre: "CM UNIDAD 60 x 60", formato: "Unidad", precioUnitario: 165.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10247482", nombre: "CM UNIDAD 80 x 80", formato: "Unidad", precioUnitario: 220.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10717826", nombre: "CM UNIDAD 60 x 60", formato: "Unidad", precioUnitario: 274.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10717833", nombre: "CM UNIDAD 80 x 80", formato: "Unidad", precioUnitario: 330.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "12102478", nombre: "CM UNIDAD Para ventana de 55 x 98", formato: "Unidad", precioUnitario: 85.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "12102480", nombre: "CM UNIDAD Para ventana de 78 x 98", formato: "Unidad", precioUnitario: 90.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10473904", nombre: "CM UNIDAD Para ventana de 114 x 118", formato: "Unidad", precioUnitario: 118.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10697316", nombre: "CM UNIDAD 60 x 50 cm", formato: "Unidad", precioUnitario: 119.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10697323", nombre: "CM UNIDAD 80 x 60 cm", formato: "Unidad", precioUnitario: 150.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10697330", nombre: "CM UNIDAD 80 x 80 cm", formato: "Unidad", precioUnitario: 160.0, categoriaId: "herramientas", subcategoria: "General", paginaCatalogo: 386 },
  { sku: "10488331", nombre: "ESTANTERÍA METÁLICA 320 kg 13", formato: "Unidad", precioUnitario: 0.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10708796", nombre: "ESTANTERÍA METÁLICA máxima: 160 kg 13", formato: "Unidad", precioUnitario: 0.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10922961", nombre: "ESTANTERÍA METÁLICA ESTANTERÍA METÁLICA máxima: 500 kg 13 máxima: 720 kg 13", formato: "Unidad", precioUnitario: 0.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10834985", nombre: "ESTANTERÍA METÁLICA ESTANTERÍA METÁLICA máxima: 500 kg 13 máxima: 720 kg 13", formato: "Unidad", precioUnitario: 0.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10933083", nombre: "ESTANTERIA METALICA 320 kg. 13", formato: "Unidad", precioUnitario: 0.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10834992", nombre: "ESTANTERÍA METÁLICA máxima: 900 kg 13", formato: "Unidad", precioUnitario: 0.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067338", nombre: "CM UNIDAD 60", formato: "Unidad", precioUnitario: 2.14, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067337", nombre: "CM UNIDAD 80", formato: "Unidad", precioUnitario: 2.86, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067336", nombre: "CM UNIDAD 100", formato: "Unidad", precioUnitario: 3.54, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067340", nombre: "CM UNIDAD 30", formato: "Unidad", precioUnitario: 1.07, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067342", nombre: "CM UNIDAD 40", formato: "Unidad", precioUnitario: 1.38, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067339", nombre: "CM UNIDAD 50", formato: "Unidad", precioUnitario: 1.78, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977785", nombre: "CM UNIDAD CM UNIDAD 3.5 x 3.5 x 200   3.5 x 3.5 x 250", formato: "Unidad", precioUnitario: 6.36, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977792", nombre: "CM UNIDAD CM UNIDAD 3.5 x 3.5 x 200   3.5 x 3.5 x 250", formato: "Unidad", precioUnitario: 6.36, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10051790", nombre: "CAJA UNIDAD", formato: "Unidad", precioUnitario: 0.53, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977743", nombre: "CAJA UNIDAD", formato: "Unidad", precioUnitario: 0.49, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977806", nombre: "CM UNIDAD 3.5 x 3.5 x 300", formato: "Unidad", precioUnitario: 7.2, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10051762", nombre: "BOLSA UNIDAD", formato: "Unidad", precioUnitario: 0.17, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "25067341", nombre: "CM UNIDAD 4.0 x 4.0 x 200", formato: "Unidad", precioUnitario: 7.98, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977764", nombre: "CM UNIDAD CM UNIDAD CM UNIDAD 60 x 30   80 x 30   100 x 30", formato: "Unidad", precioUnitario: 9.4, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977750", nombre: "CM UNIDAD CM UNIDAD CM UNIDAD 60 x 30   80 x 30   100 x 30", formato: "Unidad", precioUnitario: 9.4, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977715", nombre: "CM UNIDAD CM UNIDAD CM UNIDAD 60 x 30   80 x 30   100 x 30", formato: "Unidad", precioUnitario: 9.4, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10051643", nombre: "CM UNIDAD CM UNIDAD CM UNIDAD BALDA METAL 60 x 40   80 x 40   100 x 40", formato: "Unidad", precioUnitario: 13.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977722", nombre: "CM UNIDAD CM UNIDAD CM UNIDAD BALDA METAL 60 x 40   80 x 40   100 x 40", formato: "Unidad", precioUnitario: 13.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10977771", nombre: "CM UNIDAD CM UNIDAD CM UNIDAD BALDA METAL 60 x 40   80 x 40   100 x 40", formato: "Unidad", precioUnitario: 13.0, categoriaId: "almacenamiento", subcategoria: "General", paginaCatalogo: 112 },
  { sku: "10964590", nombre: "BOTE LITRO Blanco    de juntas de dilatación.", formato: "Unidad", precioUnitario: 17.5, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10906126", nombre: "BOTE LITRO Traslúcida    Transparente   BOTE", formato: "Unidad", precioUnitario: 17.5, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10964611", nombre: "BOTE LITRO", formato: "Unidad", precioUnitario: 0.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10906133", nombre: "BOTE LITRO Blanco    Negro    Traslúcida", formato: "Unidad", precioUnitario: 16.33, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25120299", nombre: "BOTE LITRO Blanco    Negro    Traslúcida", formato: "Unidad", precioUnitario: 16.33, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25055096", nombre: "BOTE LITRO Blanco    Negro    Traslúcida", formato: "Unidad", precioUnitario: 16.33, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25023850", nombre: "PACK WC FORMENTERA COMPAC Pack Wc en porcelana blanca.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10745805", nombre: "PACK WC MANACOR Pack Wc en porcelana blanca.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25077841", nombre: "PACK WC EGEO Pack WC en porcelana blanca.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25101359", nombre: "PACK WC NOA Pack WC en porcelana blanca.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25113851", nombre: "PACK WC COMPACTO Pack WC en porcelana blanca.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25094374", nombre: "UNIDAD Inodoro. Salida vertical", formato: "Unidad", precioUnitario: 58.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25094375", nombre: "UNIDAD Inodoro. Salida horizontal", formato: "Unidad", precioUnitario: 58.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25094379", nombre: "UNIDAD Cisterna lateral", formato: "Unidad", precioUnitario: 98.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25094378", nombre: "UNIDAD Cisterna inferior", formato: "Unidad", precioUnitario: 98.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25096100", nombre: "UNIDAD Tapa WC amortiguada", formato: "Unidad", precioUnitario: 40.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10299905", nombre: "UNIDAD Inodoro. Salida horizontal", formato: "Unidad", precioUnitario: 112.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10299912", nombre: "UNIDAD Inodoro. Salida vertical", formato: "Unidad", precioUnitario: 112.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10624040", nombre: "UNIDAD Cisterna lateral", formato: "Unidad", precioUnitario: 121.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25033830", nombre: "UNIDAD Tapa WC amortiguada", formato: "Unidad", precioUnitario: 86.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25050735", nombre: "UNIDAD Inodoro. Salida dual", formato: "Unidad", precioUnitario: 129.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25050736", nombre: "UNIDAD Cisterna inferior.", formato: "Unidad", precioUnitario: 129.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25050776", nombre: "UNIDAD Tapa WC amortiguada", formato: "Unidad", precioUnitario: 99.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "25075705", nombre: "UNIDAD Inodoro. Salida dual", formato: "Unidad", precioUnitario: 145.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10302481", nombre: "UNIDAD Cisterna inferior", formato: "Unidad", precioUnitario: 121.0, categoriaId: "banos", subcategoria: "General", paginaCatalogo: 192 },
  { sku: "10492174", nombre: "BOBINA ESTAÑO- PLATA 8% plata, 92% estaño. Sin plomo.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10402791", nombre: "BOBINA ESTAÑO PLOMO-COBRE 6% cobre, 94% Estaño-plomo.", formato: "Unidad", precioUnitario: 0.0, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10656730", nombre: "Ø MM M UNIDAD METRO 12 1 25", formato: "Unidad", precioUnitario: 5.32, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10524514", nombre: "Ø MM M UNIDAD METRO 15 25 /", formato: "Unidad", precioUnitario: 6.6, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10412066", nombre: "Ø MM M UNIDAD METRO 15 25 /", formato: "Unidad", precioUnitario: 6.6, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10412073", nombre: "Ø MM M UNIDAD METRO 18 25 /", formato: "Unidad", precioUnitario: 8.04, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10524521", nombre: "Ø MM M UNIDAD METRO 18 25 /", formato: "Unidad", precioUnitario: 8.04, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10316236", nombre: "Ø MM UNIDAD 12-1/2”", formato: "Unidad", precioUnitario: 0.9, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10316243", nombre: "Ø MM UNIDAD 15-1/2”", formato: "Unidad", precioUnitario: 0.85, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10316250", nombre: "Ø MM UNIDAD 18-1/2”", formato: "Unidad", precioUnitario: 1.0, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10316264", nombre: "Ø MM UNIDAD 15-3/4”", formato: "Unidad", precioUnitario: 1.3, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10316271", nombre: "Ø MM UNIDAD 18-3/4”", formato: "Unidad", precioUnitario: 1.3, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10316285", nombre: "Ø MM UNIDAD 22-3/4”", formato: "Unidad", precioUnitario: 1.4, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "25074502", nombre: "Ø MM UNIDAD 28-1” 1   21,65", formato: "Unidad", precioUnitario: 2.7, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10492132", nombre: "Ø MM UNIDAD 702 100g Si Si Baja presión", formato: "Unidad", precioUnitario: 15.15, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10492146", nombre: "Ø MM UNIDAD 702 250g Si Si Baja presión", formato: "Unidad", precioUnitario: 32.0, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10492153", nombre: "Ø MM UNIDAD 704 100g Si Si Baja presión", formato: "Unidad", precioUnitario: 18.5, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10492160", nombre: "Ø MM UNIDAD 704 250g Si Si Baja presión", formato: "Unidad", precioUnitario: 39.5, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360546", nombre: "Ø MM PIEZAS BOLSA UNIDAD 12-1/2” 1", formato: "Unidad", precioUnitario: 0.9, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360553", nombre: "Ø MM PIEZAS BOLSA UNIDAD 15-1/2” 2", formato: "Unidad", precioUnitario: 0.68, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360560", nombre: "Ø MM PIEZAS BOLSA UNIDAD 18-1/2” 2", formato: "Unidad", precioUnitario: 0.75, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360574", nombre: "Ø MM PIEZAS BOLSA UNIDAD 22-1/2” 1", formato: "Unidad", precioUnitario: 1.15, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360581", nombre: "Ø MM PIEZAS BOLSA UNIDAD 15-3/4” 1", formato: "Unidad", precioUnitario: 1.25, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360595", nombre: "Ø MM PIEZAS BOLSA UNIDAD 18-3/4” 1", formato: "Unidad", precioUnitario: 1.1, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10360602", nombre: "Ø MM PIEZAS BOLSA UNIDAD 22-3/4” 1", formato: "Unidad", precioUnitario: 1.4, categoriaId: "fontaneria", subcategoria: "General", paginaCatalogo: 242 },
  { sku: "10876803", nombre: "CALENTADORES 1 1 1 1 Modulante. 1 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10866695", nombre: "CALENTADORES 1 1 1 1 Modulante. 1 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "12096749", nombre: "CALENTADORES 1 1 1 1 Modulante. 1 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25118826", nombre: "CALENTADORES 1 1 1 1 Modulante. 1 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25024627", nombre: "CALENTADORES 1 1 1 1 Modulante. 1 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25118825", nombre: "CALENTADORES 1 1 1 1 Modulante. 1 1", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10699283", nombre: "GAS UNIDAD GAS UNIDAD Natural   Butano       Natural   Butano", formato: "Unidad", precioUnitario: 329.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10699346", nombre: "GAS UNIDAD GAS UNIDAD Natural   Butano       Natural   Butano", formato: "Unidad", precioUnitario: 329.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25061293", nombre: "GAS UNIDAD GAS UNIDAD Natural   Butano       Natural   Butano", formato: "Unidad", precioUnitario: 329.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25061285", nombre: "GAS UNIDAD GAS UNIDAD Natural   Butano       Natural   Butano", formato: "Unidad", precioUnitario: 329.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25024770", nombre: "GAS UNIDAD GAS UNIDAD Natural   Butano       Natural   Butano", formato: "Unidad", precioUnitario: 329.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25024760", nombre: "GAS UNIDAD GAS UNIDAD Natural   Butano       Natural   Butano", formato: "Unidad", precioUnitario: 329.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25112875", nombre: "GAS UNIDAD GAS UNIDAD Natural D23   Butano D31   Natural   Butano   Natural   Butano", formato: "Unidad", precioUnitario: 429.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25112876", nombre: "GAS UNIDAD GAS UNIDAD Natural D23   Butano D31   Natural   Butano   Natural   Butano", formato: "Unidad", precioUnitario: 429.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25057190", nombre: "GAS UNIDAD GAS UNIDAD Natural D23   Butano D31   Natural   Butano   Natural   Butano", formato: "Unidad", precioUnitario: 429.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25057099", nombre: "GAS UNIDAD GAS UNIDAD Natural D23   Butano D31   Natural   Butano   Natural   Butano", formato: "Unidad", precioUnitario: 429.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25112874", nombre: "GAS UNIDAD GAS UNIDAD Natural D23   Butano D31   Natural   Butano   Natural   Butano", formato: "Unidad", precioUnitario: 429.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "25112878", nombre: "GAS UNIDAD GAS UNIDAD Natural D23   Butano D31   Natural   Butano   Natural   Butano", formato: "Unidad", precioUnitario: 429.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10105263", nombre: "TUBO DE EVACUACIÓN", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10105130", nombre: "TUBO DE EVACUACIÓN 50   50   50   100 1   100 1   100 1", formato: "Unidad", precioUnitario: 12.45, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10164070", nombre: "TUBO DE EVACUACIÓN 50   50   50   100 1   100 1   100 1", formato: "Unidad", precioUnitario: 12.45, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10164182", nombre: "TUBO DE EVACUACIÓN 50   50   50   100 1   100 1   100 1", formato: "Unidad", precioUnitario: 12.45, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10105214", nombre: "TUBO DE EVACUACIÓN 50   50   50   100 1   100 1   100 1", formato: "Unidad", precioUnitario: 12.45, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10105326", nombre: "TUBO DE EVACUACIÓN 50   50   50   100 1   100 1   100 1", formato: "Unidad", precioUnitario: 12.45, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10164105", nombre: "TUBO DE EVACUACIÓN", formato: "Unidad", precioUnitario: 0.0, categoriaId: "energia", subcategoria: "General", paginaCatalogo: 328 },
  { sku: "10982202", nombre: "SISTEMAS DE FIJACION", formato: "Unidad", precioUnitario: 0.17, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10982146", nombre: "SISTEMAS DE FIJACION", formato: "Unidad", precioUnitario: 0.19, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10128300", nombre: "TORNILLERÍA", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10412542", nombre: "TORNILLERÍA 100", formato: "Unidad", precioUnitario: 0.1, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10412556", nombre: "TORNILLERÍA 6 x 100 100", formato: "Unidad", precioUnitario: 0.14, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10376135", nombre: "TORNILLERÍA 3 x 16 1.000", formato: "Unidad", precioUnitario: 10.0, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957142", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3,5 x 13 500    4.8 x 120 100", formato: "Unidad", precioUnitario: 0.2, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957373", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3,5 x 13 500    4.8 x 120 100", formato: "Unidad", precioUnitario: 0.2, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957156", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD TORNILLO PUNTA BROCA DIN 7504P", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957240", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3,5 x 16 500   4.8 x 16 250", formato: "Unidad", precioUnitario: 0.02, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957135", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3,5 x 9,5 1000    4.8 x 19 250", formato: "Unidad", precioUnitario: 0.03, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957254", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3,5 x 9,5 1000    4.8 x 19 250", formato: "Unidad", precioUnitario: 0.03, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956736", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 13 500    4.2 x 25 250    3,9 x 16 500    4.8 x 25 250", formato: "Unidad", precioUnitario: 0.03, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956820", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 13 500    4.2 x 25 250    3,9 x 16 500    4.8 x 25 250", formato: "Unidad", precioUnitario: 0.03, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957191", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 13 500    4.2 x 25 250    3,9 x 16 500    4.8 x 25 250", formato: "Unidad", precioUnitario: 0.03, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957261", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 13 500    4.2 x 25 250    3,9 x 16 500    4.8 x 25 250", formato: "Unidad", precioUnitario: 0.03, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957163", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957275", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD", formato: "Unidad", precioUnitario: 0.0, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956743", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 16 500    4.2 x 32 250    3.5 x 19 500   4.8 x 38 500", formato: "Unidad", precioUnitario: 0.04, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956855", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 16 500    4.2 x 32 250    3.5 x 19 500   4.8 x 38 500", formato: "Unidad", precioUnitario: 0.04, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956750", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 19 500    4.8 x 16 250    3.9 x 13 500    4.8 x 50 250", formato: "Unidad", precioUnitario: 0.05, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956883", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 19 500    4.8 x 16 250    3.9 x 13 500    4.8 x 50 250", formato: "Unidad", precioUnitario: 0.05, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957170", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 19 500    4.8 x 16 250    3.9 x 13 500    4.8 x 50 250", formato: "Unidad", precioUnitario: 0.05, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10957324", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 19 500    4.8 x 16 250    3.9 x 13 500    4.8 x 50 250", formato: "Unidad", precioUnitario: 0.05, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 },
  { sku: "10956764", nombre: "MM UDS CAJA UNIDAD MM UDS CAJA UNIDAD 3.5 x 25 250    4.8 x 19 250    4,2 x 13 500    4.8 x 63 200", formato: "Unidad", precioUnitario: 0.06, categoriaId: "ferreteria", subcategoria: "General", paginaCatalogo: 456 }
];
